{{- if .Values.secrets.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.secrets.externalSecret.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "backend-platform.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.secrets.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.secrets.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.secrets.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ include "backend-platform.fullname" . }}-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_USER
      remoteRef:
        key: backend-platform/db
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: backend-platform/db
        property: password
    - secretKey: DB_NAME
      remoteRef:
        key: backend-platform/db
        property: database
    - secretKey: JWT_SECRET
      remoteRef:
        key: backend-platform/app
        property: jwtSecret
    - secretKey: DEFAULT_TENANT_API_KEY
      remoteRef:
        key: backend-platform/app
        property: defaultTenantApiKey
    - secretKey: DEFAULT_LOGIN_PASSWORD
      remoteRef:
        key: backend-platform/app
        property: defaultLoginPassword
{{- end }}
