{{- if and .Values.secrets.create (not .Values.secrets.existingSecretName) (not .Values.secrets.externalSecret.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend-platform.fullname" . }}-secrets
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "backend-platform.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USER: {{ .Values.global.db.user | quote }}
  DB_PASSWORD: {{ .Values.global.db.password | quote }}
  DB_NAME: {{ .Values.global.db.name | quote }}
  JWT_SECRET: {{ .Values.global.jwtSecret | quote }}
  DEFAULT_TENANT_API_KEY: {{ .Values.global.tenant.defaultApiKey | quote }}
  DEFAULT_LOGIN_PASSWORD: {{ .Values.global.tenant.defaultPassword | quote }}
{{- end }}
